FROM registry.access.redhat.com/ubi8/openjdk-17@sha256:c6e2ab901ab94190b632d603c1e56e3d2f401883294ca7911eb3cd0d746f7a0f AS builder

WORKDIR /work
COPY ./ .

RUN mvn -V -B package -pl cli -am -DskipTests

FROM registry.access.redhat.com/ubi8/openjdk-17-runtime@sha256:1f15011cccf53f31591b2675c9967f50cec1434c212888a55916cbfdf3ccaf9d
WORKDIR /work/

COPY --from=builder /work/cli/target/quarkus-app/lib/ /deployments/lib/
COPY --from=builder /work/cli/target/quarkus-app/*.jar /deployments/
COPY --from=builder /work/cli/target/quarkus-app/app/ /deployments/app/
COPY --from=builder /work/cli/target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 0

ENV AB_JOLOKIA_OFF=""
ENV JAVA_OPTS="-Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"
